'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Ecogames.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Crucigrama.
        '''</summary>
        Friend ReadOnly Property ActivityType_Crossword() As String
            Get
                Return ResourceManager.GetString("ActivityType_Crossword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.
        '''</summary>
        Friend ReadOnly Property ActivityType_Crossword_ID() As String
            Get
                Return ResourceManager.GetString("ActivityType_Crossword_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ahorcado.
        '''</summary>
        Friend ReadOnly Property ActivityType_Hangman() As String
            Get
                Return ResourceManager.GetString("ActivityType_Hangman", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.
        '''</summary>
        Friend ReadOnly Property ActivityType_Hangman_ID() As String
            Get
                Return ResourceManager.GetString("ActivityType_Hangman_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preguntas abiertas.
        '''</summary>
        Friend ReadOnly Property ActivityType_Question_Open() As String
            Get
                Return ResourceManager.GetString("ActivityType_Question_Open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend ReadOnly Property ActivityType_Question_Open_ID() As String
            Get
                Return ResourceManager.GetString("ActivityType_Question_Open_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preguntas con opciones.
        '''</summary>
        Friend ReadOnly Property ActivityType_Question_Opts() As String
            Get
                Return ResourceManager.GetString("ActivityType_Question_Opts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend ReadOnly Property ActivityType_Question_Opts_ID() As String
            Get
                Return ResourceManager.GetString("ActivityType_Question_Opts_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Referencia.
        '''</summary>
        Friend ReadOnly Property Crossword_ColumnHeader_ReferenceText() As String
            Get
                Return ResourceManager.GetString("Crossword_ColumnHeader_ReferenceText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property drawing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("drawing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La evaluación automática no es totalmente precisa y puede dar resultados erróneos..
        '''</summary>
        Friend ReadOnly Property Question_Open_AutoEvalWarn() As String
            Get
                Return ResourceManager.GetString("Question_Open_AutoEvalWarn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar.
        '''</summary>
        Friend ReadOnly Property Question_Opts_DelMode() As String
            Get
                Return ResourceManager.GetString("Question_Opts_DelMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vas a eliminar esta opción, ¿estás seguro?.
        '''</summary>
        Friend ReadOnly Property Question_Opts_Empty() As String
            Get
                Return ResourceManager.GetString("Question_Opts_Empty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}
        '''
        '''Cuando termines, hacé clic en &quot;Guardar&quot;..
        '''</summary>
        Friend ReadOnly Property Question_Opts_GeneralHelp() As String
            Get
                Return ResourceManager.GetString("Question_Opts_GeneralHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar.
        '''</summary>
        Friend ReadOnly Property Question_Opts_ModMode() As String
            Get
                Return ResourceManager.GetString("Question_Opts_ModMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Nueva respuesta&gt;.
        '''</summary>
        Friend ReadOnly Property Question_Opts_NewAnswer() As String
            Get
                Return ResourceManager.GetString("Question_Opts_NewAnswer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Para configurar las respuestas, hacé clic en &quot;Siguiente&quot;..
        '''</summary>
        Friend ReadOnly Property Question_Opts_NextActionHelp() As String
            Get
                Return ResourceManager.GetString("Question_Opts_NextActionHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Para agregar una opción, hacé clic en &quot;Agregar&quot;..
        '''</summary>
        Friend ReadOnly Property Question_Opts_NextAnswerHelp() As String
            Get
                Return ResourceManager.GetString("Question_Opts_NextAnswerHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guardado.
        '''</summary>
        Friend ReadOnly Property Question_Saved() As String
            Get
                Return ResourceManager.GetString("Question_Saved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agregar.
        '''</summary>
        Friend ReadOnly Property Queston_Add() As String
            Get
                Return ResourceManager.GetString("Queston_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Actividad.
        '''</summary>
        Friend ReadOnly Property Settings_Activity() As String
            Get
                Return ResourceManager.GetString("Settings_Activity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El valor ingresado &quot;{0}&quot; está reservado para el sistema..
        '''</summary>
        Friend ReadOnly Property Settings_Crossword_IllegalStringException() As String
            Get
                Return ResourceManager.GetString("Settings_Crossword_IllegalStringException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se estableció una referencia..
        '''</summary>
        Friend ReadOnly Property Settings_Crossword_NoReference() As String
            Get
                Return ResourceManager.GetString("Settings_Crossword_NoReference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar todo.
        '''</summary>
        Friend ReadOnly Property Settings_General_DeleteAllText() As String
            Get
                Return ResourceManager.GetString("Settings_General_DeleteAllText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Alto ahí! Vas a borrar todo, ¿estás seguro?.
        '''</summary>
        Friend ReadOnly Property Settings_General_DeleteAllWarn() As String
            Get
                Return ResourceManager.GetString("Settings_General_DeleteAllWarn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar.
        '''</summary>
        Friend ReadOnly Property Settings_General_DeleteText() As String
            Get
                Return ResourceManager.GetString("Settings_General_DeleteText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ocurrió un error interno..
        '''</summary>
        Friend ReadOnly Property Settings_General_Err() As String
            Get
                Return ResourceManager.GetString("Settings_General_Err", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El índice {0} de {1} no es un número..
        '''</summary>
        Friend ReadOnly Property Settings_General_Err_Index() As String
            Get
                Return ResourceManager.GetString("Settings_General_Err_Index", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend ReadOnly Property Settings_General_Err_Title() As String
            Get
                Return ResourceManager.GetString("Settings_General_Err_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Nueva actividad&gt;.
        '''</summary>
        Friend ReadOnly Property Settings_General_NewActivity() As String
            Get
                Return ResourceManager.GetString("Settings_General_NewActivity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No hay ninguna actividad..
        '''</summary>
        Friend ReadOnly Property Settings_General_NoActivities() As String
            Get
                Return ResourceManager.GetString("Settings_General_NoActivities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vas a perder tus cambios, ¿querés salir de todos modos?.
        '''</summary>
        Friend ReadOnly Property Settings_General_UnsavedWarn() As String
            Get
                Return ResourceManager.GetString("Settings_General_UnsavedWarn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Advertencia.
        '''</summary>
        Friend ReadOnly Property Settings_General_Warn_Title() As String
            Get
                Return ResourceManager.GetString("Settings_General_Warn_Title", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
