'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Ecogames.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Crucigrama.
        '''</summary>
        Friend ReadOnly Property ActivityType_Crossword() As String
            Get
                Return ResourceManager.GetString("ActivityType_Crossword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.
        '''</summary>
        Friend ReadOnly Property ActivityType_Crossword_ID() As String
            Get
                Return ResourceManager.GetString("ActivityType_Crossword_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ahorcado.
        '''</summary>
        Friend ReadOnly Property ActivityType_Hangman() As String
            Get
                Return ResourceManager.GetString("ActivityType_Hangman", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.
        '''</summary>
        Friend ReadOnly Property ActivityType_Hangman_ID() As String
            Get
                Return ResourceManager.GetString("ActivityType_Hangman_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preguntas abiertas.
        '''</summary>
        Friend ReadOnly Property ActivityType_Question_Open() As String
            Get
                Return ResourceManager.GetString("ActivityType_Question_Open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend ReadOnly Property ActivityType_Question_Open_ID() As String
            Get
                Return ResourceManager.GetString("ActivityType_Question_Open_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preguntas con opciones.
        '''</summary>
        Friend ReadOnly Property ActivityType_Question_Opts() As String
            Get
                Return ResourceManager.GetString("ActivityType_Question_Opts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend ReadOnly Property ActivityType_Question_Opts_ID() As String
            Get
                Return ResourceManager.GetString("ActivityType_Question_Opts_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Referencia.
        '''</summary>
        Friend ReadOnly Property Crossword_ColumnHeader_ReferenceText() As String
            Get
                Return ResourceManager.GetString("Crossword_ColumnHeader_ReferenceText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property drawing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("drawing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Las contraseñas no coinciden..
        '''</summary>
        Friend ReadOnly Property FirstRun_PasswordsDontMatch() As String
            Get
                Return ResourceManager.GetString("FirstRun_PasswordsDontMatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La contraseña es muy corta..
        '''</summary>
        Friend ReadOnly Property FirstRun_PasswordTooShort() As String
            Get
                Return ResourceManager.GetString("FirstRun_PasswordTooShort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tenés que introducir un nombre..
        '''</summary>
        Friend ReadOnly Property FirstRun_UsernameRequired() As String
            Get
                Return ResourceManager.GetString("FirstRun_UsernameRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend ReadOnly Property General_Error_Title() As String
            Get
                Return ResourceManager.GetString("General_Error_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Información.
        '''</summary>
        Friend ReadOnly Property General_Info_Title() As String
            Get
                Return ResourceManager.GetString("General_Info_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Advertencia.
        '''</summary>
        Friend ReadOnly Property General_Warn_Title() As String
            Get
                Return ResourceManager.GetString("General_Warn_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La contraseña que ingresaste es incorrecta, por favor intentálo otra vez..
        '''</summary>
        Friend ReadOnly Property Login_WrongPassword() As String
            Get
                Return ResourceManager.GetString("Login_WrongPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Muy bien! Completaste una fila..
        '''</summary>
        Friend ReadOnly Property Play_Crossword_RowDone() As String
            Get
                Return ResourceManager.GetString("Play_Crossword_RowDone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conseguiste {0}/{1} puntos (un {2}%)..
        '''</summary>
        Friend ReadOnly Property Play_General_CompletionLevel() As String
            Get
                Return ResourceManager.GetString("Play_General_CompletionLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (vacío).
        '''</summary>
        Friend ReadOnly Property Play_General_EmptyAnswerDescriptor() As String
            Get
                Return ResourceManager.GetString("Play_General_EmptyAnswerDescriptor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Comienza la partida!.
        '''</summary>
        Friend ReadOnly Property Play_General_GameBegins() As String
            Get
                Return ResourceManager.GetString("Play_General_GameBegins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No completaste la actividad, ¿querés salir de todos modos?.
        '''</summary>
        Friend ReadOnly Property Play_General_IncompleteActivityWarn() As String
            Get
                Return ResourceManager.GetString("Play_General_IncompleteActivityWarn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Te quedaste sin intentos!.
        '''</summary>
        Friend ReadOnly Property Play_General_NoAttempts() As String
            Get
                Return ResourceManager.GetString("Play_General_NoAttempts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No conseguiste ningún punto..
        '''</summary>
        Friend ReadOnly Property Play_General_NoCompletion() As String
            Get
                Return ResourceManager.GetString("Play_General_NoCompletion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Felicidades! Completaste la actividad con un puntaje perfecto..
        '''</summary>
        Friend ReadOnly Property Play_General_PerfectScore() As String
            Get
                Return ResourceManager.GetString("Play_General_PerfectScore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Perfecto!.
        '''</summary>
        Friend ReadOnly Property Play_General_PerfectScore_Trim() As String
            Get
                Return ResourceManager.GetString("Play_General_PerfectScore_Trim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Te quedan {0} segundos..
        '''</summary>
        Friend ReadOnly Property Play_General_RemainingSeconds_Plural() As String
            Get
                Return ResourceManager.GetString("Play_General_RemainingSeconds_Plural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Te queda {0} segundo..
        '''</summary>
        Friend ReadOnly Property Play_General_RemainingSeconds_Singular() As String
            Get
                Return ResourceManager.GetString("Play_General_RemainingSeconds_Singular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Correcto!.
        '''</summary>
        Friend ReadOnly Property Play_General_RightAnswer() As String
            Get
                Return ResourceManager.GetString("Play_General_RightAnswer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uh, ¡te quedaste sin tiempo!.
        '''</summary>
        Friend ReadOnly Property Play_General_Timedout() As String
            Get
                Return ResourceManager.GetString("Play_General_Timedout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uh, ¡te equivocaste!.
        '''</summary>
        Friend ReadOnly Property Play_General_WrongAnswer() As String
            Get
                Return ResourceManager.GetString("Play_General_WrongAnswer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Incorrecto! Te quedan {0} intentos..
        '''</summary>
        Friend ReadOnly Property Play_Hangman_Wrong_RemainingAttempts() As String
            Get
                Return ResourceManager.GetString("Play_Hangman_Wrong_RemainingAttempts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tu respuesta estaba vacía y no obtuviste puntos (completaste un {0}%)..
        '''</summary>
        Friend ReadOnly Property Play_Question_General_AutoEvalEmpty() As String
            Get
                Return ResourceManager.GetString("Play_Question_General_AutoEvalEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No respondiste, ¿querés continuar de todos modos?.
        '''</summary>
        Friend ReadOnly Property Play_Question_General_AutoEvalEmptyAnswerWarn() As String
            Get
                Return ResourceManager.GetString("Play_Question_General_AutoEvalEmptyAnswerWarn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Muy bien! Lograste un {0}%..
        '''</summary>
        Friend ReadOnly Property Play_Question_General_AutoEvalRegular() As String
            Get
                Return ResourceManager.GetString("Play_Question_General_AutoEvalRegular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Excelente, ¡seguí así! Sacaste un {0}%..
        '''</summary>
        Friend ReadOnly Property Play_Question_General_AutoEvalRight() As String
            Get
                Return ResourceManager.GetString("Play_Question_General_AutoEvalRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Uh! Conseguiste apenas un {0}%..
        '''</summary>
        Friend ReadOnly Property Play_Question_General_AutoEvalWrong() As String
            Get
                Return ResourceManager.GetString("Play_Question_General_AutoEvalWrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡No conseguiste ningún punto! {0}% completado..
        '''</summary>
        Friend ReadOnly Property Play_Question_Open_AutoEvalNoScore() As String
            Get
                Return ResourceManager.GetString("Play_Question_Open_AutoEvalNoScore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tu respuesta: 
        '''{0}
        '''
        '''Respuesta esperada: 
        '''{1}.
        '''</summary>
        Friend ReadOnly Property Play_Question_Open_AutoEvalResult() As String
            Get
                Return ResourceManager.GetString("Play_Question_Open_AutoEvalResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor, esperá a que la respuesta sea evaluada personalmente por el profesor..
        '''</summary>
        Friend ReadOnly Property Play_Question_Open_NoAutoEvalInfo() As String
            Get
                Return ResourceManager.GetString("Play_Question_Open_NoAutoEvalInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Gracias por responder!.
        '''</summary>
        Friend ReadOnly Property Play_Question_Open_NoAutoEvalThanks() As String
            Get
                Return ResourceManager.GetString("Play_Question_Open_NoAutoEvalThanks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Podés responder seleccionando todas las opciones que creas correctas..
        '''</summary>
        Friend ReadOnly Property Play_Question_Opts_GeneralHelp() As String
            Get
                Return ResourceManager.GetString("Play_Question_Opts_GeneralHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La evaluación automática no es totalmente precisa y puede dar resultados erróneos..
        '''</summary>
        Friend ReadOnly Property Question_Open_AutoEvalWarn() As String
            Get
                Return ResourceManager.GetString("Question_Open_AutoEvalWarn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar.
        '''</summary>
        Friend ReadOnly Property Question_Opts_DelMode() As String
            Get
                Return ResourceManager.GetString("Question_Opts_DelMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vas a eliminar esta opción, ¿estás seguro?.
        '''</summary>
        Friend ReadOnly Property Question_Opts_Empty() As String
            Get
                Return ResourceManager.GetString("Question_Opts_Empty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}
        '''
        '''Cuando termines, hacé clic en &quot;Guardar&quot;..
        '''</summary>
        Friend ReadOnly Property Question_Opts_GeneralHelp() As String
            Get
                Return ResourceManager.GetString("Question_Opts_GeneralHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar.
        '''</summary>
        Friend ReadOnly Property Question_Opts_ModMode() As String
            Get
                Return ResourceManager.GetString("Question_Opts_ModMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Nueva respuesta&gt;.
        '''</summary>
        Friend ReadOnly Property Question_Opts_NewAnswer() As String
            Get
                Return ResourceManager.GetString("Question_Opts_NewAnswer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Para configurar las respuestas, hacé clic en &quot;Siguiente&quot;..
        '''</summary>
        Friend ReadOnly Property Question_Opts_NextActionHelp() As String
            Get
                Return ResourceManager.GetString("Question_Opts_NextActionHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Para agregar una opción, hacé clic en &quot;Agregar&quot;..
        '''</summary>
        Friend ReadOnly Property Question_Opts_NextAnswerHelp() As String
            Get
                Return ResourceManager.GetString("Question_Opts_NextAnswerHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guardado.
        '''</summary>
        Friend ReadOnly Property Question_Saved() As String
            Get
                Return ResourceManager.GetString("Question_Saved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agregar.
        '''</summary>
        Friend ReadOnly Property Queston_Add() As String
            Get
                Return ResourceManager.GetString("Queston_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Actividad.
        '''</summary>
        Friend ReadOnly Property Settings_Activity() As String
            Get
                Return ResourceManager.GetString("Settings_Activity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El valor ingresado &quot;{0}&quot; está reservado para el sistema..
        '''</summary>
        Friend ReadOnly Property Settings_Crossword_IllegalStringException() As String
            Get
                Return ResourceManager.GetString("Settings_Crossword_IllegalStringException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se estableció una referencia..
        '''</summary>
        Friend ReadOnly Property Settings_Crossword_NoReference() As String
            Get
                Return ResourceManager.GetString("Settings_Crossword_NoReference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar todo.
        '''</summary>
        Friend ReadOnly Property Settings_General_DeleteAllText() As String
            Get
                Return ResourceManager.GetString("Settings_General_DeleteAllText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Alto ahí! Vas a borrar todo, ¿querés continuar?.
        '''</summary>
        Friend ReadOnly Property Settings_General_DeleteAllWarn() As String
            Get
                Return ResourceManager.GetString("Settings_General_DeleteAllWarn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar.
        '''</summary>
        Friend ReadOnly Property Settings_General_DeleteText() As String
            Get
                Return ResourceManager.GetString("Settings_General_DeleteText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ocurrió un error interno..
        '''</summary>
        Friend ReadOnly Property Settings_General_Err() As String
            Get
                Return ResourceManager.GetString("Settings_General_Err", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El índice {0} de {1} no es un número..
        '''</summary>
        Friend ReadOnly Property Settings_General_Err_Index() As String
            Get
                Return ResourceManager.GetString("Settings_General_Err_Index", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Nueva actividad&gt;.
        '''</summary>
        Friend ReadOnly Property Settings_General_NewActivity() As String
            Get
                Return ResourceManager.GetString("Settings_General_NewActivity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No hay ninguna actividad..
        '''</summary>
        Friend ReadOnly Property Settings_General_NoActivities() As String
            Get
                Return ResourceManager.GetString("Settings_General_NoActivities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vas a perder tus cambios, ¿querés salir de todos modos?.
        '''</summary>
        Friend ReadOnly Property Settings_General_UnsavedWarn() As String
            Get
                Return ResourceManager.GetString("Settings_General_UnsavedWarn", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
